Add reviews
jaggerPwn/java-filmorate-group pull request #4
Opened 2023-06-22 15:22 UTC by jaggerPwn

2023-06-22 20:33 UTC, AleXx313 requested changes

2023-06-22 20:33 UTC, AleXx313 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +        return ReviewMapper.reviewToDTO(review);
Тут получается экземпляр review с присвоенным id появляется только в  return.
Возможно нужно до return создать объект reviewDTO, чтобы я мог выдернуть из него id и после этого передать этот экземпляр в return.

2023-06-22 20:35 UTC, AleXx313 approved these changes

2023-06-23 17:28 UTC, AleXx313 approved these changes

2023-06-23 17:55 UTC, AKnazzz reviewed
Хороший рабочий код! Молодец ! Есть некоторые вопросы с логированием + некоторые решения можно немного подправить! В целом хорошо
НО
+ не написал два эндпоинта = их надо доделать

2023-06-23 17:55 UTC, AKnazzz commented on src/main/resources/schema.sql
> +    content VARCHAR(200) NOT NULL,
По логике если review - это обзор фильма, то может убрать ограничение в 200 символов ? Т.к. часто обзоры бывают гораздо больше.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Получен POST запрос по эндпоинту '/reviews' на публикацию поста");
Не критичное замечание по стилю - мне ревьюер предлагал не использовать русские аналогии сущностей - т.е. чтобы код был понятен даже в международной команде - лучше использовать именно REVIEWS. 
далее подобные замечания не буду указывать. 
те есть сущность  REVIEW - у тебя по коду встречается ПОСТ, REVIEW, ОТЗЫВ, РЕВЬЮ.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Получен GET запрос по эндпоинту '/reviews/{reviewId}' на получение поста " + reviewId);
лучше переписать с подстановкой значения в стиле проекта
log.info("Получен GET запрос по эндпоинту '/reviews/{reviewId}' на получение review с ID {} ", reviewId);

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void deleteFilmById(@PathVariable Long filmId) {
Это метод на delete Film по ID в ReviewController ? - надо изменить название метода + логирование + эндпоинт (нет эндпоинта  "/reviews/{filmId}")

Логика написана правильно

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<List<ReviewDTO>> getAllReviews(
Не критично - Для лучшей читаемости называл бы метод getAllReviewsByFilmId, иначе если не знать кода можно понять что получение вообще всех Reviews

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
Не хватает двух эндпоинтов 
       DELETE /reviews/{id}/like/{userId} — пользователь удаляет лайк/дизлайк отзыву.
       DELETE /reviews/{id}/dislike/{userId} — пользователь удаляет дизлайк отзыву.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    final ReviewService reviewService;
поставить модификатор private

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/dto/ReviewDTO.java
> +    private int useful;
Сделать валидация с помощью аннотация = тогда нам вообще не нужен дополнительный метод в классе Validator.

@Data
@Builder
public class ReviewDTO {
        private Long reviewId;
        @NotBlank
        private String content;
        @JsonProperty(value = "isPositive")
        @NotNull
        private Boolean isPositive;
        @NotNull    
        private Long userId;
        @NotNull    
        private Long filmId;
        @JsonProperty(value = "useful")
        private int useful;

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            @RequestParam(value = "count", defaultValue = "10", required = false) Long count) {
нет смысла добавлять value = "filmId" и value = "count" если называние переменной совпадает с параметром в URL

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<ReviewDTO> getReview(@PathVariable Long reviewId) {
Для лучшей читаемости лучше называть метод getReviewById

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return new ResponseEntity<>(reviewService.addReview(reviewDTO), HttpStatus.OK);
Не критично - т.к. Постман тесты прошли но для создания сущности используют статус HttpStatus.CREATED

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Получен GET запрос по эндпоинту '/reviews' на получение всех постов ");
можно попробовать в логировании написать Film Id - тогда если он не задан будет Null и при анализе кода будет видно бы ли ID и COUNT в запросе.

 log.info("Получен GET запрос по эндпоинту '/reviews' на получение  REVIEWS  в кол-ве {} для FILM c ID {}", count, filmId);

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                "на лайк поста %d юзером%d", reviewId, userId));
Предлагаю написать логирование в стиле проекта без использования String.format

log.info("Получен PUT запрос по эндпоинту '/reviews/{reviewId}/like/{userId}' на лайк поста {} юзером {}", reviewId, userId);

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                "на DISлайк поста %d юзером%d", reviewId, userId));
см. замечание выше - переделать логирование в стиле проекта.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/validation/Validator.java
> +    public static boolean reviewValidator(Review review) {
Если мы проставим все аннотации для валидации в классе DTO = то этот метод совсем не требуется
Валидация требуется для тех случаев которые мы не можем проверить аннотаций спринга = я знаю что у Юзера и Фильма часть можно тоже удалить в методе = предлагаю это оставить на финальное ревью перед сдачей  + там мы уберём логирование в сервисе = оставим только на уровне контроллеров и сторадж + изменим структуру папок проекта.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/dto/ReviewDTO.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
Вопрос для чего здесь используется эта аннотация?

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +    public ReviewServiceImpl(@Qualifier("reviewDbStorage") ReviewStorage rs, UserService us) {
@Qualifier("reviewDbStorage") - лишний т.к. у нас только одна реализация интерфейса - т.е. реализации InMemory нет

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +        log.debug("получен запрос на добавление Review ");
У тебя в одном месте сущность называет Отзывы - в этом Review  - предлагаю сделать в одном стиле.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +    public void deleteReviewById(Long filmId) {
полагаю тут не filmId, а reviewId

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +        log.debug("Получен запрос на добавление лайка");
log.debug("Получен запрос на добавление  отзыва  к Review c ID {} от User c ID {}", reviewId, userId);

Т.к. метод написан как для лайка так и для дизлайка - то в логировании нельзя однозначно указать - что там лайк = всё зависит от значения positive. Можно попробовать реализовать через ветвление - тода будет два залогированных случая.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewServiceImpl.java
> +        log.debug("получен запрос на получение ревью по фильму ID c {}", filmId);
третье название - отзыв,review, ревью - предлагаю везде использовать одно наименование

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +            return statement;
почему не хочешь написать используя simpleJdbc ?
было бы меньше строчек кода и проще пишется 
 аналогично методу 

    @Override
    public User saveUser(User user) {
        SimpleJdbcInsert simpleJdbcInsert = new SimpleJdbcInsert(jdbcTemplate).withTableName("users")
                .usingGeneratedKeyColumns("id");
        Number key = simpleJdbcInsert.executeAndReturnKey(user.userToMap());
        user.setId((Long) key);
        log.debug("User создан с ID {}.", user.getId());
        return user;
    }

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public Review saveReview(Review review) {
тут у тебя нет проверки на то что User и Film есть в нашей БД = т.е. по идее можно залит отзыв несуществующего Юзера на несуществующий фильм

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        log.debug("Отзыв создан");
Предлагаю написать более детально логирование в стиле проекта 
log.debug("Review  на Film c ID {} от User c ID {} создано", review.getFilmId(),review.getUserId());

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        log.debug("Отзыв получен");
Предлагаю написать более детально логирование в стиле проекта 
log.debug("Review с ID {}  на Film c ID {} от User c ID {} получено",review.getReviewId() ,review.getFilmId(),review.getUserId());

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        if (count == null) count = 10L;
эта строчка не используется у тебя в контроллере уже задано значение 10 по дефолту

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        List<Review> reviews = null;
List<Review> reviews - для чего его задавать null - мы дальше его инициализируем - это не используется

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        log.debug("Отзывы получены");
Предлагаю написать более детально логирование в стиле проекта
log.debug("Reviews на Film c ID {} получены.",filmId);

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        sql = "INSERT INTO reviewLikes (REVIEWID, USERID, POSITIVE) VALUES(?, ?, ?)";
Я запутался - для чего ты сначала DELETE все а потом INSERT?
Почему не использовать UPDATE?

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        log.debug("Лайки сохранены");
Тут могут быть и дизлайки
log.debug("Реакция на Review c ID {} от User c ID {} сохранены",reviewId, userId);

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        log.debug("Отзыв обновлен");
log.debug("Review c ID {} обновлен", review.getReviewId());

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        log.debug("Отзыв удален");
log.debug("Review c ID {} удалён", id);

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    void saveReviewLikes(Long reviewId, Long userId, boolean positive);
не хватает метода - на нём 2 эндпоинта по ТЗ
void deleteReviewLikes(Long reviewId, Long userId, boolean positive);

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +            String sqlQuery = "SELECT R.ID,\n" +
для чего использовать \n если можно перенести просто через Enter?
запрос все равно будет считываться одной строкой.

2023-06-23 17:55 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public void saveReviewLikes(Long reviewId, Long userId, boolean positive) {
saveReviewLikesOrDislikes

2023-06-23 17:56 UTC, AKnazzz reviewed
Хороший рабочий код! Молодец ! Есть некоторые вопросы с логированием + некоторые решения можно немного подправить! В целом хорошо
НО
+ не написал два эндпоинта = их надо доделать

2023-06-23 18:42 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void deleteFilmById(@PathVariable Long filmId) {
поправил наименования , но не понял почему нет эндпоинта "/reviews/{filmId}"

2023-06-23 18:44 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<List<ReviewDTO>> getAllReviews(
наверное это ты про другой метод, но тебя понял. Поправил в другом месте

2023-06-23 18:59 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/dto/ReviewDTO.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
Пережитки прошлого кода

2023-06-23 19:01 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/validation/Validator.java
> +    public static boolean reviewValidator(Review review) {
я пытался на уровне DTO аннотации расставлять, но они не всегда возвращали нужный код ошибки. Если подскажешь как в определенных случаях через аннотацию кидать 404 а в других 400 было бы супер

2023-06-23 19:13 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +            return statement;
Обсуждаемо.. я вот заленился писать reviewToMap в классе review ради одной реализации. Но если есть опасения что не примут, то давай поправим.

2023-06-23 19:17 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public Review saveReview(Review review) {
В целом не получится, база не даст из-за того что связи будут нарушены. но давай добавлю проверку.

2023-06-23 19:26 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        sql = "INSERT INTO reviewLikes (REVIEWID, USERID, POSITIVE) VALUES(?, ?, ?)";
да...)

2023-06-23 19:29 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +            String sqlQuery = "SELECT R.ID,\n" +
Я запросы сначала все в DBeaver делаю, а оттуда так копируется( я вообще ленивый по природе, поэтому не удаляю=)

2023-06-23 20:29 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public void deleteFilmById(@PathVariable Long filmId) {
Я так понимаю мы удаляем конкретное Review по reviewId = аналогично удалению User и Film = просто само название  можно оставить как filmId = но оно сбивает с толку - можно понять что удаляются все Reviews для filmId

2023-06-23 20:38 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/validation/Validator.java
> +    public static boolean reviewValidator(Review review) {
Да, конечно - для этого в классе KingHandler ))) есть ResponseStatusException = там модно задавать конкретный код при его выбрасывании: пример = тут установили код 404 = но можно выбросить тот который требуется по тестам


   @Override
    public Genre readById(Integer id) {
        String sqlQuery = "SELECT * FROM genres WHERE id = ?";

        if (id == null) {
            throw new ValidationException("Невозможно выполнить запрос с пустым аргументом.");
        }
        try {
            return jdbcTemplate.queryForObject(sqlQuery, this::mapToGenre, id);
        } catch (Throwable e) {
            throw new ResponseStatusException(HttpStatus.valueOf(404), "Нет такого Genre");
        }
    }

2023-06-23 20:44 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<List<ReviewDTO>> getAllReviews(
Согласен можно оставить

2023-06-23 20:57 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +            return statement;
У тебя код работает (есть правило если работает то не трогай) - но по мне сложно написано = с simpleJdbcInsert  было бы 4 строчки = можем потом отрефакторить на финише. а сам метод reviewToMap по мне написать проще (и короче) чем код выше. Но если хочешь можешь оставить

2023-06-23 21:03 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        sql = "INSERT INTO reviewLikes (REVIEWID, USERID, POSITIVE) VALUES(?, ?, ?)";
Но сначала он удаляет **все** записи о лайках для данного отзыва, а затем добавляет новую запись с указанным пользователем и значением лайка (положительный или отрицательный). А если там будут стоять лайки других пользователей?

2023-06-23 21:04 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +            String sqlQuery = "SELECT R.ID,\n" +
А я думаю = что ты их везде расставил - мне было бы лень их прописывать так)))

2023-06-24 14:26 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/dto/ReviewDTO.java
> +    private int useful;
Аннотации я расставил, но не получается валидаторы убрать.

2023-06-24 14:31 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/validation/Validator.java
> +    public static boolean reviewValidator(Review review) {
KingHandler прекрасен спору нет) но убрать вообще метод валидатора я пока не приложу ума как.. точнее приложу, но тогда идёт всё наперекосяк по тестам.

2023-06-24 14:33 UTC, jaggerPwn commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        sql = "INSERT INTO reviewLikes (REVIEWID, USERID, POSITIVE) VALUES(?, ?, ?)";
Точно, добавил AND USERID = ?

2023-06-24 19:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        sql = "INSERT INTO reviewLikes (REVIEWID, USERID, POSITIVE) VALUES(?, ?, ?)";
Для того чтобы пользователь передумал - он должен отправить другой запрос - который также будет через UPDATE. В твоём коде удалятся все лайки всех пользователей.

2023-06-24 21:23 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public Review saveReview(Review review) {
@Override
    public Review saveReview(Review review) {
       // Validator.reviewValidator(review);
        fs.getFilmById(review.getFilmId());
        us.getUserById(review.getUserId());
        KeyHolder keyHolder = new GeneratedKeyHolder();
        String sqlInsert = "INSERT INTO PUBLIC.\"REVIEWS\"\n" +
                "(content, ispositive, userid, filmid)" +
                "VALUES (?, ?, ?, ?)";
        jdbcTemplate.update(con -> {
            PreparedStatement statement = con.prepareStatement(sqlInsert, new String[]{"ID"});
            statement.setString(1, review.getContent());
            statement.setBoolean(2, review.getIsPositive());
            statement.setLong(3, review.getUserId());
            statement.setLong(4, review.getFilmId());
            return statement;
        }, keyHolder);
        try {
            review.setReviewId(keyHolder.getKey().longValue());
        } catch (InvalidDataAccessApiUsageException | NullPointerException e) {
            throw new ValidationException("key not assigned");
        }
        log.debug("Отзыв на Film c ID {} от User c ID {} создан", review.getFilmId(), review.getUserId());
        return review;
    }

2023-06-24 21:24 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public Review saveReview(Review review) {
можно использовать методы получения film/user по id,ибо в них уже заложена проверка на существовании записи в БД,таким образом мы не только проверяем что ID положительные, но и существуют в БД. Иначе из постмана можно подать любой положительный ID и мы добавим запись не проверяю её на существование.

и получится, что несуществующий пользователь может добавить отзыв к несуществующему фильму.

2023-06-24 21:26 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        sql = "INSERT INTO reviewLikes (REVIEWID, USERID, POSITIVE) VALUES(?, ?, ?)";
Т.е. User не может передумать в процессе запроса = а чтобы изменить своё мнение - он подаёт новый запрос = надо переписать с использованием UPDATE

2023-06-24 21:27 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/validation/Validator.java
> +    public static boolean reviewValidator(Review review) {
Теперь с правками выше этот метод вообще не требуется = лишний код можно удалить.

2023-06-25 07:53 UTC, AKnazzz approved these changes
Отлично! Все замечания устранены! По спорным моментам - нашли решения!

2023-06-25 08:10 UTC, merged