Add search
jaggerPwn/java-filmorate-group pull request #5
Opened 2023-06-23 17:33 UTC by casumazu

2023-06-23 17:59 UTC, AleXx313 requested changes

2023-06-23 17:59 UTC, AleXx313 commented on src/main/java/ru/yandex/practicum/filmorate/dto/DirectorsDTO.java
У нас ведь уже есть в develop классы Director и DirectorDTO. Нужно работать с ними) Свои не нужно создавать.

2023-06-23 17:59 UTC, AleXx313 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +    public List<Film> searchFilm(String query, String by) {
Этот метод больше похож на метод сервиса. Он не взаимодействует с базой и содержит скорее бизнес логику. 
Предлагаю перенести его в слой service

2023-06-23 17:59 UTC, AleXx313 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +    public List<Film> topFilms(){
Топ фильмами вроде Родион занимается) Дай и ему немного покодить)

2023-06-23 18:21 UTC, AKnazzz reviewed
Я посмотрю более детально - постараюсь или сегодня позже или завтра)

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
добавить логирование

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<List<FilmDTO>> getAllFilms() {
добавить логирование

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +    public List<Film> topFilms(){
Это старый метод - он был в прошлом ТЗ Родион должен его переработать с учетом новый условий и моделей

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/dto/DirectorsDTO.java
Да я думаю надо было предварительно запшуить самый последний код - чтобы не было конфликтов

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        log.debug("Получены все Film по имени режиссёра");
log.debug("Получены все Film по имени Director {}.", queryStr );

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        log.debug("Получены все Film по названию");
написать логирования аналогично см. выше - со вставкой  значения

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +    public List<Film> searchFilmForDirector(String queryStr){
Как будет отработан случай если имя директора отсутствует в бд?

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        log.debug("Получены все Film по названию и режиссёру");
написать логирования аналогично см. выше - со вставкой значения

2023-06-23 18:21 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +    public List<Film> searchFilmForTitleAndDirector(String queryStr){
Как будет отработан случай если имя директора и название отсутствует в бд?

2023-06-24 18:34 UTC, AleXx313 approved these changes

2023-06-24 21:39 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<List<FilmDTO>> getAllFilms() {
Т.к. переделываем логику для одного эндпоинта = этот код удалить. Логика на слое storage.

2023-06-24 21:43 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    public List<FilmDTO> getTopFilms(Long count) {
для чего этот метод если есть аналогичный см. строчки с 85-89 . Удалить лишний

2023-06-24 21:45 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +            return Collections.emptyList(); // or throw an exception
предлагаю переписать на строчку = тогда нам не потребуется твой второй эндпоинт

      return new ArrayList<>(fs.getTopFilms(null));

2023-06-24 21:48 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    List<FilmDTO> getTopFilms(Long count);
удалить т.к. есть аналогичный метод readTopFilms

2023-06-24 21:59 UTC, AKnazzz reviewed
Хороший код = всё написано понятно = все тесты пройдены = предлагаю немного скорректировать логику - немного скорректировать метод поиска = удалить лишний метод. В целом всё супер!

2023-06-24 21:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +        return FilmMapper.listFilmsToListDto(search(query, by));
не критично = возможно в методе search переделать тип возвращаемого значения на List<FilmDTO>  = тогда придётся везде в return добавить FilmMapper.listFilmsToListDto (.....) = тогда этот метод не потребуется

2023-06-24 21:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    public List<FilmDTO> getTopFilms(Long count) {
для чего этот метод если есть аналогичный см. строчки с 85-89 . Удалить лишний

2023-06-24 21:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +            return Collections.emptyList(); // or throw an exception
предлагаю переписать на строчку = тогда нам не потребуется твой второй эндпоинт

  return new ArrayList<>(fs.getTopFilms(null));

2023-06-24 21:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    List<FilmDTO> getTopFilms(Long count);
удалить т.к. есть аналогичный метод readTopFilms

2023-06-24 21:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<List<FilmDTO>> getAllFilms() {
В ТЗ указан один эндпоинт - его можно обработать в рамках одного метода = логику ниже немного скорректировал - в целом всё отлично!
Т.к. переделываем логику для одного эндпоинта = этот код удалить. Логика на слое storage.

2023-06-24 21:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ResponseEntity<>(service.searchFilm(query,by), HttpStatus.OK);
Оба твоих метода searchFilmForDirector и getAllFilms можно сделать в одном эндпоинте:

2023-06-24 21:59 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ResponseEntity<>(service.searchFilm(query,by), HttpStatus.OK);
@GetMapping("search")
public ResponseEntity<List> searchFilmForDirector(@RequestParam(required = false) String query,
@RequestParam(required = false, defaultValue = "title") String by) {
log.info("Получен GET запрос по эндпоинту '/films/search/' на получение по списка фильмов по " +
"называнию {} и/или режиссеру {} .", query, by);
return new ResponseEntity<>(service.searchFilm(query, by), HttpStatus.OK);
}

2023-06-24 22:00 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +        log.debug("Получены все Film по названию");
log.debug("Получены все Film по названию {}", queryStr);

2023-06-24 22:03 UTC, AKnazzz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDBStorage.java
> +    public List<Film> searchFilm(String query, String by) {
не критично = возможно в методе search переделать тип возвращаемого значения на List FilmDTO = тогда придётся везде в return добавить FilmMapper.listFilmsToListDto (.....) = тогда этот метод не потребуется

2023-06-25 10:49 UTC, casumazu commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ResponseEntity<>(service.searchFilm(query,by), HttpStatus.OK);
спасибо, даже как-то не подумал об этом

2023-06-25 13:41 UTC, AKnazzz approved these changes
Отличный код! Все замечания устранены! Весь функционал успешно прошёл тестирования!

2023-06-25 18:20 UTC, jaggerPwn approved these changes
все круто

2023-06-25 19:19 UTC, merged